{% set name = "hachoir-metadata" %}
{% set version = "1.3.3" %}

package:
  name: {{ name }}
  version: {{ version }}

source:
  fn: {{ name }}-{{ version }}.tar.gz
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/{{ name }}-{{ version }}.tar.gz
  sha256: ec403f13a44e2cf3d26001f8f440cdc4329a316a4c971035944bfadacc90eb3c

build:
  skip: True  # [py3k]
  number: 1001
  script: {{ PYTHON }} -m pip install . --no-deps -vv

requirements:
  host:
    - python

  run:
    - python
    - hachoir-core
    - hachoir-parser

test:
  imports:
    - hachoir_metadata
    - hachoir_metadata.qt

about:
  home: http://bitbucket.org/haypo/hachoir/wiki/hachoir-metadata
  license: GPL 2.0
  summary: 'Program to extract metadata using Hachoir library'

extra:
  recipe-maintainers:
    - pmlandwehr
