travis:
  secure:
    BINSTAR_TOKEN: bdUiKxlL+ffjzna1SFIvHe1a7S6ugdeUQWsE7lKjmJhe/MZs7Ragg19x485dHEUe7zPXC+Sm+CSQjX3/CPJjbP3cO4n5fPbrXKfp3aA8ItV3TzETl+ZKQAve2xez/ae40CK1nrkxUVhKaXGJvV/2kg5VccrtstS8sJ/dELYKdHLHk5LiXbHzAfHowxRzRzLFQnBpUVmCb0R0fB/U27ERBoxzyKitCIxoI0CIFfj/9rk0vo5eyLhk0+18hKsvOpDUuHC2W5ZihEo8XwGOaswlnTJ9w1dUPvhrUv9xiUZpLRyPn8R2khjvcGLv73mlwpZ+KZi52tPJNTe0I07NHta7Xm7/KfoILV6wdHtn3ApUA4CbO7zQx5I6UyjSJ/64iFPib9e/ffhRXuZAvW8hNYD1CzVuWggQ/jcowKUacAQp0cbypfz/M8cNKBN8yFTjwJUuBkHGVPYje2+90sJVqIJeIEPIO2ohFCcM9RjCyNwXyutBpMtXH4Db8/+BTvZgKnqJmQ5UivRNEg1mpURkEnjrH5LjLGSZrGLxZMx5g0uIQvVbNP3mKGh9fxh5BBkSMgVv5qmDnxhcQ99LSrWNWBohHSEhglDU5ZMZ3OhjIRVC7YBGs6/1sLUJeFMeMWjy7StaO+HdQS1yFCGCi/QbnfFvOGtS/XahYK2r2kTZ6yFf40Y=
appveyor:
  secure:
    BINSTAR_TOKEN: ipv/06DzgA7pzz2CIAtbPxZSsphDtF+JFyoWRnXkn3O8j7oRe3rzqj3LOoq2DZp4
