appveyor:
  secure: {BINSTAR_TOKEN: tumuXLL8PU75WMnRDemRy02ruEq2RpNxeK3dz0MjFssnosPm2v4EFjfNB4PTotA1}
compiler_stack: comp7
max_py_ver: '37'
max_r_ver: '35'
travis:
  secure: {BINSTAR_TOKEN: yakpAivN94Q7d2ex4g3GX78gqrW84+Ji7DQyTELmpu1ustJ1eN69V0zmBIKA40e1aZNlsTznUWQG5AYed9HcILbIuWGDpUjXgTy4c3T2wVCkCxk2bGEwiRu37u7SwxQPVeixVAWwA9kqOgcy3AjCjnp6jc0nY2mz8nVSIWIC9KRyrPnZ1IvabURNcAYt9DZvAku9Cm6pf++Vag/fo4vIuvHgLAn53DNSev8qL/Ud2+7a43gCRrT6oOt+UVfVJUGRAomiZtnoHeiCBEmqDuVyyL4kYzqftU7llG7C7o++pvIacn5FF2LEu3K5x4SZmX4EoY1MJDVYiHk+9beixi2nmdODVOL5u/5iJ2y6l67bn0zEbQdCrNvn2qaWx+CIFpqmB6df0YOaWFSoQD768S2KR6DvWLro7VrZTPd7DQZDYX5fQnZ/oAyLBMbivQzciEfn4FTtjVcHMGuyhnQKnGTLHqot1DtaqaImGn69Qdi07F3sJCMThTIv2B8etmpW4qeLrrlq65Cr04QEKNMUc9m0njnQw75WC6cHVBS0xzrC48SyshMqrmKUz7+Uu8G0S4M5tt0p1npcJT0hSNW1V/8IMcCPXsg6oXENkAdfgzXzvirZSVAH3rZ6Q0IwxUp1NYlI0HIKz8RLGOhv0JkSVYcOQmQG/lFLhSVm+u/WGtUlUek=}
conda_forge_output_validation: true
